name: Deploy to AWS CloudFormation

on:
  push:
    branches:
      - aws-action-deploy
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'eu-west-2'
        keypair:
          description: 'SSH Key Pair'
          required: true

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region}}

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: MyStack
        template: ec2_stack_template.yaml