name: Deploy to AWS CloudFormation

on:
  push:
    branches:
      - aws-action-deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
      with:
        name: Package
    - name: Deployment
      env:
        PRIVATE_KEY: ${{ secrets.AWS_PEM  }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ls -a
        ssh -o StrictHostKeyChecking=no -i private_key ec2-user@ec2-34-211-87-105.us-west-2.compute.amazonaws.com
        scp -i private_key Package ec2-user@ec2-34-211-87-105.us-west-2.compute.amazonaws.com:~/
