on:
  push:
    paths:
      - 'ec2_stack_template.yaml'

jobs:
  update_stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test run
        run: |
          ls -a
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Create AWS CloudFormation Stack
        run: |
          aws cloudformation create-stack --stack-name SurveyAppStack --template-body file://ec2_stack_template.yaml
