name: Java CI with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          GITHUB_CONTEXT: ${{ github.event.head_commit.message }}
        run: |
          git fetch --tags
          echo ##################
          version=$(git tag --sort=committerdate | tail -n 1)
          echo "Version:::::::::"
          echo $version
          version_array=( ${version//./ } )
          major="${version_array[0]}"
          minor="${version_array[1]}"
          echo "minor $minor"
          patch="${version_array[2]}"
          echo "patch $patch"
          echo $version
          str="feature"
          branch=($GITHUB_CONTEXT)
          if [[ $branch == feature* ]] ;
          then
            ((minor = minor + 1))
          elif [[ $branch == fix* ]] ;
          then
            ((patch = patch + 1))
          fi
          echo $major.$minor.$patch
          echo "TAG=$major.$minor.$patch" >> $GITHUB_ENV
          ./gradlew build -x test
      - name: Advance nightly tag
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.TAG }}",
              sha: context.sha
            })
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
  remove-old-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old artifacts
        uses: Remagpie/gha-remove-artifact@v1
        with:
          max-count: 3