name: Java CI with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          GITHUB_CONTEXT: ${{ github.event.head_commit.message }}
        run: |
          git fetch --tags
          echo ##################
          version=$(git tag --sort=committerdate | tail -n 1)
          echo "Version:::::::::"
          echo $version
          version_array=( ${version//./ } )
          major="${version_array[0]}"
          minor="${version_array[1]}"
          echo "minor $minor"
          patch="${version_array[2]}"
          echo "patch $patch"
          echo $version
          #!/bin/bash
          str="feature"
          branch=($GITHUB_CONTEXT)
          echo $branch
          echo ${branch[0]}
          if [[ $str == feature* ]] ;
          then
            ((minor = minor + 1))
          fi
          echo $major.$minor.$patch
          ./gradlew build -x test
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2