name: Java CI with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.head_commit.message) }}
        run: |
          git fetch --tags
          echo ##################
          version= $(git tag --sort=committerdate | tail -n 1)
          echo "Version:::::::::"
          echo $version
          a=( ${version//./ } )
          ((a[2]++))
          version="${a[2]}"
          echo $version
          ./gradlew build -x test
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2